// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCf2U73dxsr43E7jMXdY2KleWXFHsGqO5Y',
    appId: '1:859516771932:web:657ffef6946b970aaf9099',
    messagingSenderId: '859516771932',
    projectId: 'inventorysystem-a7ea8',
    authDomain: 'inventorysystem-a7ea8.firebaseapp.com',
    storageBucket: 'inventorysystem-a7ea8.firebasestorage.app',
    measurementId: 'G-8Y0CY4L40B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArE5z81N3x-1-KvKVR1MTcgfu0YMkrYlg',
    appId: '1:859516771932:android:5a33d9aab62eebeaaf9099',
    messagingSenderId: '859516771932',
    projectId: 'inventorysystem-a7ea8',
    storageBucket: 'inventorysystem-a7ea8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCL7leQI-WvUbez9i5vnPm0RTmkLBbnAIE',
    appId: '1:859516771932:ios:9e8f335b0381e56caf9099',
    messagingSenderId: '859516771932',
    projectId: 'inventorysystem-a7ea8',
    storageBucket: 'inventorysystem-a7ea8.firebasestorage.app',
    iosBundleId: 'com.example.inventorySystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCL7leQI-WvUbez9i5vnPm0RTmkLBbnAIE',
    appId: '1:859516771932:ios:9e8f335b0381e56caf9099',
    messagingSenderId: '859516771932',
    projectId: 'inventorysystem-a7ea8',
    storageBucket: 'inventorysystem-a7ea8.firebasestorage.app',
    iosBundleId: 'com.example.inventorySystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCf2U73dxsr43E7jMXdY2KleWXFHsGqO5Y',
    appId: '1:859516771932:web:d55f1d0e1bbbfc92af9099',
    messagingSenderId: '859516771932',
    projectId: 'inventorysystem-a7ea8',
    authDomain: 'inventorysystem-a7ea8.firebaseapp.com',
    storageBucket: 'inventorysystem-a7ea8.firebasestorage.app',
    measurementId: 'G-ESBR4H86XG',
  );
}
